version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "9090:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      - "TB_QUEUE_TYPE=in-memory"
      - "VIRTUAL_HOST=thingsboard.${DOMAIN_BASE}" 
      - "VIRTUAL_PORT=9090"
      - "LETSENCRYPT_HOST=thingsboard.${DOMAIN_BASE}"
      - "LETSENCRYPT_EMAIL=${DOMAIN_EMAIL}" 
    volumes:
      - ./data:/data
      - ./logs:/var/log/thingsboard

networks:
  default:
    external:
      name: nginx-proxy
